---
- hosts: all
  gather_facts: false
  vars:
    backup_base: "/home/wideawake/ansible_backup/backup/"

  tasks:
    - name: Create backup directories
      ansible.builtin.file:
        path: "{{ backup_base }}{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost

    - name: Perform backups
      ansible.builtin.synchronize:
        src: "{{ item.path }}"
        dest: "{{ backup_base }}{{ inventory_hostname }}"
        mode: pull
        rsync_path: "sudo rsync"
        rsync_opts: "-R {{ rsync_options | default('--exclude-from lin-excludes.txt') }}"
        #rsync_opts: "-R {{ rsync_options | default(omit) }}"
      with_items: "{{ src_paths }}"
      delegate_to: localhost
